/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoleSelectionRouteImport } from './routes/role-selection'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiCareerRecommendationsRouteImport } from './routes/api/career-recommendations'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiJobMatchRouteImport } from './routes/api/job-match'
import { Route as ApiRecruiterAiRouteImport } from './routes/api/recruiter-ai'
import { Route as ApiRecruiterReviewRouteImport } from './routes/api/recruiter-review'
import { Route as ApiResumeAnalysisRouteImport } from './routes/api/resume-analysis'
import { Route as ApiSkillGapRouteImport } from './routes/api/skill-gap'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as CandidateAnalyticsRouteImport } from './routes/candidate/analytics'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate/applications'
import { Route as CandidateInterviewPrepRouteImport } from './routes/candidate/interview-prep'
import { Route as CandidateInterviewsRouteImport } from './routes/candidate/interviews'
import { Route as CandidateOnboardingRouteImport } from './routes/candidate/onboarding'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as CandidateResumeRouteImport } from './routes/candidate/resume'
import { Route as CandidateResumeAnalyzerRouteImport } from './routes/candidate/resume-analyzer'
import { Route as CandidateSettingsRouteImport } from './routes/candidate/settings'
import { Route as CandidateSkillGapRouteImport } from './routes/candidate/skill-gap'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter/index'
import { Route as RecruiterAiRouteImport } from './routes/recruiter/ai'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter/analytics'
import { Route as RecruiterApplicantsRouteImport } from './routes/recruiter/applicants'
import { Route as RecruiterInterviewsRouteImport } from './routes/recruiter/interviews'
import { Route as RecruiterOnboardingRouteImport } from './routes/recruiter/onboarding'
import { Route as RecruiterPipelineRouteImport } from './routes/recruiter/pipeline'
import { Route as RecruiterSettingsRouteImport } from './routes/recruiter/settings'
import { Route as CandidateJobsIndexRouteImport } from './routes/candidate/jobs/index'
import { Route as CandidateJobsJobIdRouteImport } from './routes/candidate/jobs/$jobId'
import { Route as RecruiterCandidatesCandidateIdRouteImport } from './routes/recruiter/candidates/$candidateId'
import { Route as RecruiterJobsIndexRouteImport } from './routes/recruiter/jobs/index'
import { Route as RecruiterJobsJobIdRouteImport } from './routes/recruiter/jobs/$jobId'
import { Route as RecruiterJobsNewRouteImport } from './routes/recruiter/jobs/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectionRoute = RoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareerRecommendationsRoute =
  ApiCareerRecommendationsRouteImport.update({
    id: '/api/career-recommendations',
    path: '/api/career-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobMatchRoute = ApiJobMatchRouteImport.update({
  id: '/api/job-match',
  path: '/api/job-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecruiterAiRoute = ApiRecruiterAiRouteImport.update({
  id: '/api/recruiter-ai',
  path: '/api/recruiter-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecruiterReviewRoute = ApiRecruiterReviewRouteImport.update({
  id: '/api/recruiter-review',
  path: '/api/recruiter-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeAnalysisRoute = ApiResumeAnalysisRouteImport.update({
  id: '/api/resume-analysis',
  path: '/api/resume-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillGapRoute = ApiSkillGapRouteImport.update({
  id: '/api/skill-gap',
  path: '/api/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAnalyticsRoute = CandidateAnalyticsRouteImport.update({
  id: '/candidate/analytics',
  path: '/candidate/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateInterviewPrepRoute = CandidateInterviewPrepRouteImport.update({
  id: '/candidate/interview-prep',
  path: '/candidate/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateInterviewsRoute = CandidateInterviewsRouteImport.update({
  id: '/candidate/interviews',
  path: '/candidate/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateOnboardingRoute = CandidateOnboardingRouteImport.update({
  id: '/candidate/onboarding',
  path: '/candidate/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateResumeRoute = CandidateResumeRouteImport.update({
  id: '/candidate/resume',
  path: '/candidate/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateResumeAnalyzerRoute = CandidateResumeAnalyzerRouteImport.update({
  id: '/candidate/resume-analyzer',
  path: '/candidate/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSettingsRoute = CandidateSettingsRouteImport.update({
  id: '/candidate/settings',
  path: '/candidate/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSkillGapRoute = CandidateSkillGapRouteImport.update({
  id: '/candidate/skill-gap',
  path: '/candidate/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/recruiter/',
  path: '/recruiter/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterAiRoute = RecruiterAiRouteImport.update({
  id: '/recruiter/ai',
  path: '/recruiter/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/recruiter/analytics',
  path: '/recruiter/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterApplicantsRoute = RecruiterApplicantsRouteImport.update({
  id: '/recruiter/applicants',
  path: '/recruiter/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterInterviewsRoute = RecruiterInterviewsRouteImport.update({
  id: '/recruiter/interviews',
  path: '/recruiter/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterOnboardingRoute = RecruiterOnboardingRouteImport.update({
  id: '/recruiter/onboarding',
  path: '/recruiter/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterPipelineRoute = RecruiterPipelineRouteImport.update({
  id: '/recruiter/pipeline',
  path: '/recruiter/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterSettingsRoute = RecruiterSettingsRouteImport.update({
  id: '/recruiter/settings',
  path: '/recruiter/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateJobsIndexRoute = CandidateJobsIndexRouteImport.update({
  id: '/candidate/jobs/',
  path: '/candidate/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateJobsJobIdRoute = CandidateJobsJobIdRouteImport.update({
  id: '/candidate/jobs/$jobId',
  path: '/candidate/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterCandidatesCandidateIdRoute =
  RecruiterCandidatesCandidateIdRouteImport.update({
    id: '/recruiter/candidates/$candidateId',
    path: '/recruiter/candidates/$candidateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruiterJobsIndexRoute = RecruiterJobsIndexRouteImport.update({
  id: '/recruiter/jobs/',
  path: '/recruiter/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsJobIdRoute = RecruiterJobsJobIdRouteImport.update({
  id: '/recruiter/jobs/$jobId',
  path: '/recruiter/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsNewRoute = RecruiterJobsNewRouteImport.update({
  id: '/recruiter/jobs/new',
  path: '/recruiter/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/copilot': typeof CopilotRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role-selection': typeof RoleSelectionRoute
  '/signup': typeof SignupRoute
  '/api/career-recommendations': typeof ApiCareerRecommendationsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/job-match': typeof ApiJobMatchRoute
  '/api/recruiter-ai': typeof ApiRecruiterAiRoute
  '/api/recruiter-review': typeof ApiRecruiterReviewRoute
  '/api/resume-analysis': typeof ApiResumeAnalysisRoute
  '/api/skill-gap': typeof ApiSkillGapRoute
  '/candidate/analytics': typeof CandidateAnalyticsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/interview-prep': typeof CandidateInterviewPrepRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/resume-analyzer': typeof CandidateResumeAnalyzerRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/skill-gap': typeof CandidateSkillGapRoute
  '/recruiter/ai': typeof RecruiterAiRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applicants': typeof RecruiterApplicantsRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/onboarding': typeof RecruiterOnboardingRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/candidate/jobs/$jobId': typeof CandidateJobsJobIdRoute
  '/recruiter/candidates/$candidateId': typeof RecruiterCandidatesCandidateIdRoute
  '/recruiter/jobs/$jobId': typeof RecruiterJobsJobIdRoute
  '/recruiter/jobs/new': typeof RecruiterJobsNewRoute
  '/candidate/jobs/': typeof CandidateJobsIndexRoute
  '/recruiter/jobs/': typeof RecruiterJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/copilot': typeof CopilotRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role-selection': typeof RoleSelectionRoute
  '/signup': typeof SignupRoute
  '/api/career-recommendations': typeof ApiCareerRecommendationsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/job-match': typeof ApiJobMatchRoute
  '/api/recruiter-ai': typeof ApiRecruiterAiRoute
  '/api/recruiter-review': typeof ApiRecruiterReviewRoute
  '/api/resume-analysis': typeof ApiResumeAnalysisRoute
  '/api/skill-gap': typeof ApiSkillGapRoute
  '/candidate/analytics': typeof CandidateAnalyticsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/interview-prep': typeof CandidateInterviewPrepRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/resume-analyzer': typeof CandidateResumeAnalyzerRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/skill-gap': typeof CandidateSkillGapRoute
  '/recruiter/ai': typeof RecruiterAiRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applicants': typeof RecruiterApplicantsRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/onboarding': typeof RecruiterOnboardingRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/candidate': typeof CandidateIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/candidate/jobs/$jobId': typeof CandidateJobsJobIdRoute
  '/recruiter/candidates/$candidateId': typeof RecruiterCandidatesCandidateIdRoute
  '/recruiter/jobs/$jobId': typeof RecruiterJobsJobIdRoute
  '/recruiter/jobs/new': typeof RecruiterJobsNewRoute
  '/candidate/jobs': typeof CandidateJobsIndexRoute
  '/recruiter/jobs': typeof RecruiterJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/copilot': typeof CopilotRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role-selection': typeof RoleSelectionRoute
  '/signup': typeof SignupRoute
  '/api/career-recommendations': typeof ApiCareerRecommendationsRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/job-match': typeof ApiJobMatchRoute
  '/api/recruiter-ai': typeof ApiRecruiterAiRoute
  '/api/recruiter-review': typeof ApiRecruiterReviewRoute
  '/api/resume-analysis': typeof ApiResumeAnalysisRoute
  '/api/skill-gap': typeof ApiSkillGapRoute
  '/candidate/analytics': typeof CandidateAnalyticsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/interview-prep': typeof CandidateInterviewPrepRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume': typeof CandidateResumeRoute
  '/candidate/resume-analyzer': typeof CandidateResumeAnalyzerRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/skill-gap': typeof CandidateSkillGapRoute
  '/recruiter/ai': typeof RecruiterAiRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applicants': typeof RecruiterApplicantsRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/onboarding': typeof RecruiterOnboardingRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/candidate/jobs/$jobId': typeof CandidateJobsJobIdRoute
  '/recruiter/candidates/$candidateId': typeof RecruiterCandidatesCandidateIdRoute
  '/recruiter/jobs/$jobId': typeof RecruiterJobsJobIdRoute
  '/recruiter/jobs/new': typeof RecruiterJobsNewRoute
  '/candidate/jobs/': typeof CandidateJobsIndexRoute
  '/recruiter/jobs/': typeof RecruiterJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/copilot'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/reset-password'
    | '/role-selection'
    | '/signup'
    | '/api/career-recommendations'
    | '/api/copilot'
    | '/api/insights'
    | '/api/job-match'
    | '/api/recruiter-ai'
    | '/api/recruiter-review'
    | '/api/resume-analysis'
    | '/api/skill-gap'
    | '/candidate/analytics'
    | '/candidate/applications'
    | '/candidate/interview-prep'
    | '/candidate/interviews'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/candidate/resume-analyzer'
    | '/candidate/settings'
    | '/candidate/skill-gap'
    | '/recruiter/ai'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/interviews'
    | '/recruiter/onboarding'
    | '/recruiter/pipeline'
    | '/recruiter/settings'
    | '/candidate/'
    | '/recruiter/'
    | '/candidate/jobs/$jobId'
    | '/recruiter/candidates/$candidateId'
    | '/recruiter/jobs/$jobId'
    | '/recruiter/jobs/new'
    | '/candidate/jobs/'
    | '/recruiter/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/copilot'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/reset-password'
    | '/role-selection'
    | '/signup'
    | '/api/career-recommendations'
    | '/api/copilot'
    | '/api/insights'
    | '/api/job-match'
    | '/api/recruiter-ai'
    | '/api/recruiter-review'
    | '/api/resume-analysis'
    | '/api/skill-gap'
    | '/candidate/analytics'
    | '/candidate/applications'
    | '/candidate/interview-prep'
    | '/candidate/interviews'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/candidate/resume-analyzer'
    | '/candidate/settings'
    | '/candidate/skill-gap'
    | '/recruiter/ai'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/interviews'
    | '/recruiter/onboarding'
    | '/recruiter/pipeline'
    | '/recruiter/settings'
    | '/candidate'
    | '/recruiter'
    | '/candidate/jobs/$jobId'
    | '/recruiter/candidates/$candidateId'
    | '/recruiter/jobs/$jobId'
    | '/recruiter/jobs/new'
    | '/candidate/jobs'
    | '/recruiter/jobs'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/copilot'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/reset-password'
    | '/role-selection'
    | '/signup'
    | '/api/career-recommendations'
    | '/api/copilot'
    | '/api/insights'
    | '/api/job-match'
    | '/api/recruiter-ai'
    | '/api/recruiter-review'
    | '/api/resume-analysis'
    | '/api/skill-gap'
    | '/candidate/analytics'
    | '/candidate/applications'
    | '/candidate/interview-prep'
    | '/candidate/interviews'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/candidate/resume-analyzer'
    | '/candidate/settings'
    | '/candidate/skill-gap'
    | '/recruiter/ai'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/interviews'
    | '/recruiter/onboarding'
    | '/recruiter/pipeline'
    | '/recruiter/settings'
    | '/candidate/'
    | '/recruiter/'
    | '/candidate/jobs/$jobId'
    | '/recruiter/candidates/$candidateId'
    | '/recruiter/jobs/$jobId'
    | '/recruiter/jobs/new'
    | '/candidate/jobs/'
    | '/recruiter/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CopilotRoute: typeof CopilotRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoleSelectionRoute: typeof RoleSelectionRoute
  SignupRoute: typeof SignupRoute
  ApiCareerRecommendationsRoute: typeof ApiCareerRecommendationsRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiJobMatchRoute: typeof ApiJobMatchRoute
  ApiRecruiterAiRoute: typeof ApiRecruiterAiRoute
  ApiRecruiterReviewRoute: typeof ApiRecruiterReviewRoute
  ApiResumeAnalysisRoute: typeof ApiResumeAnalysisRoute
  ApiSkillGapRoute: typeof ApiSkillGapRoute
  CandidateAnalyticsRoute: typeof CandidateAnalyticsRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateInterviewPrepRoute: typeof CandidateInterviewPrepRoute
  CandidateInterviewsRoute: typeof CandidateInterviewsRoute
  CandidateOnboardingRoute: typeof CandidateOnboardingRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResumeRoute: typeof CandidateResumeRoute
  CandidateResumeAnalyzerRoute: typeof CandidateResumeAnalyzerRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
  CandidateSkillGapRoute: typeof CandidateSkillGapRoute
  RecruiterAiRoute: typeof RecruiterAiRoute
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterApplicantsRoute: typeof RecruiterApplicantsRoute
  RecruiterInterviewsRoute: typeof RecruiterInterviewsRoute
  RecruiterOnboardingRoute: typeof RecruiterOnboardingRoute
  RecruiterPipelineRoute: typeof RecruiterPipelineRoute
  RecruiterSettingsRoute: typeof RecruiterSettingsRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
  CandidateJobsJobIdRoute: typeof CandidateJobsJobIdRoute
  RecruiterCandidatesCandidateIdRoute: typeof RecruiterCandidatesCandidateIdRoute
  RecruiterJobsJobIdRoute: typeof RecruiterJobsJobIdRoute
  RecruiterJobsNewRoute: typeof RecruiterJobsNewRoute
  CandidateJobsIndexRoute: typeof CandidateJobsIndexRoute
  RecruiterJobsIndexRoute: typeof RecruiterJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-selection': {
      id: '/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof RoleSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/career-recommendations': {
      id: '/api/career-recommendations'
      path: '/api/career-recommendations'
      fullPath: '/api/career-recommendations'
      preLoaderRoute: typeof ApiCareerRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-match': {
      id: '/api/job-match'
      path: '/api/job-match'
      fullPath: '/api/job-match'
      preLoaderRoute: typeof ApiJobMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recruiter-ai': {
      id: '/api/recruiter-ai'
      path: '/api/recruiter-ai'
      fullPath: '/api/recruiter-ai'
      preLoaderRoute: typeof ApiRecruiterAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recruiter-review': {
      id: '/api/recruiter-review'
      path: '/api/recruiter-review'
      fullPath: '/api/recruiter-review'
      preLoaderRoute: typeof ApiRecruiterReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-analysis': {
      id: '/api/resume-analysis'
      path: '/api/resume-analysis'
      fullPath: '/api/resume-analysis'
      preLoaderRoute: typeof ApiResumeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skill-gap': {
      id: '/api/skill-gap'
      path: '/api/skill-gap'
      fullPath: '/api/skill-gap'
      preLoaderRoute: typeof ApiSkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/analytics': {
      id: '/candidate/analytics'
      path: '/candidate/analytics'
      fullPath: '/candidate/analytics'
      preLoaderRoute: typeof CandidateAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/interview-prep': {
      id: '/candidate/interview-prep'
      path: '/candidate/interview-prep'
      fullPath: '/candidate/interview-prep'
      preLoaderRoute: typeof CandidateInterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/interviews': {
      id: '/candidate/interviews'
      path: '/candidate/interviews'
      fullPath: '/candidate/interviews'
      preLoaderRoute: typeof CandidateInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/onboarding': {
      id: '/candidate/onboarding'
      path: '/candidate/onboarding'
      fullPath: '/candidate/onboarding'
      preLoaderRoute: typeof CandidateOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/resume': {
      id: '/candidate/resume'
      path: '/candidate/resume'
      fullPath: '/candidate/resume'
      preLoaderRoute: typeof CandidateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/resume-analyzer': {
      id: '/candidate/resume-analyzer'
      path: '/candidate/resume-analyzer'
      fullPath: '/candidate/resume-analyzer'
      preLoaderRoute: typeof CandidateResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/candidate/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/skill-gap': {
      id: '/candidate/skill-gap'
      path: '/candidate/skill-gap'
      fullPath: '/candidate/skill-gap'
      preLoaderRoute: typeof CandidateSkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/recruiter'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/ai': {
      id: '/recruiter/ai'
      path: '/recruiter/ai'
      fullPath: '/recruiter/ai'
      preLoaderRoute: typeof RecruiterAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/recruiter/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/applicants': {
      id: '/recruiter/applicants'
      path: '/recruiter/applicants'
      fullPath: '/recruiter/applicants'
      preLoaderRoute: typeof RecruiterApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/interviews': {
      id: '/recruiter/interviews'
      path: '/recruiter/interviews'
      fullPath: '/recruiter/interviews'
      preLoaderRoute: typeof RecruiterInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/onboarding': {
      id: '/recruiter/onboarding'
      path: '/recruiter/onboarding'
      fullPath: '/recruiter/onboarding'
      preLoaderRoute: typeof RecruiterOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/pipeline': {
      id: '/recruiter/pipeline'
      path: '/recruiter/pipeline'
      fullPath: '/recruiter/pipeline'
      preLoaderRoute: typeof RecruiterPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/settings': {
      id: '/recruiter/settings'
      path: '/recruiter/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof RecruiterSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/jobs/': {
      id: '/candidate/jobs/'
      path: '/candidate/jobs'
      fullPath: '/candidate/jobs/'
      preLoaderRoute: typeof CandidateJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/jobs/$jobId': {
      id: '/candidate/jobs/$jobId'
      path: '/candidate/jobs/$jobId'
      fullPath: '/candidate/jobs/$jobId'
      preLoaderRoute: typeof CandidateJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/candidates/$candidateId': {
      id: '/recruiter/candidates/$candidateId'
      path: '/recruiter/candidates/$candidateId'
      fullPath: '/recruiter/candidates/$candidateId'
      preLoaderRoute: typeof RecruiterCandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs/': {
      id: '/recruiter/jobs/'
      path: '/recruiter/jobs'
      fullPath: '/recruiter/jobs/'
      preLoaderRoute: typeof RecruiterJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs/$jobId': {
      id: '/recruiter/jobs/$jobId'
      path: '/recruiter/jobs/$jobId'
      fullPath: '/recruiter/jobs/$jobId'
      preLoaderRoute: typeof RecruiterJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs/new': {
      id: '/recruiter/jobs/new'
      path: '/recruiter/jobs/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof RecruiterJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  CopilotRoute: CopilotRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoleSelectionRoute: RoleSelectionRoute,
  SignupRoute: SignupRoute,
  ApiCareerRecommendationsRoute: ApiCareerRecommendationsRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiJobMatchRoute: ApiJobMatchRoute,
  ApiRecruiterAiRoute: ApiRecruiterAiRoute,
  ApiRecruiterReviewRoute: ApiRecruiterReviewRoute,
  ApiResumeAnalysisRoute: ApiResumeAnalysisRoute,
  ApiSkillGapRoute: ApiSkillGapRoute,
  CandidateAnalyticsRoute: CandidateAnalyticsRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateInterviewPrepRoute: CandidateInterviewPrepRoute,
  CandidateInterviewsRoute: CandidateInterviewsRoute,
  CandidateOnboardingRoute: CandidateOnboardingRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResumeRoute: CandidateResumeRoute,
  CandidateResumeAnalyzerRoute: CandidateResumeAnalyzerRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
  CandidateSkillGapRoute: CandidateSkillGapRoute,
  RecruiterAiRoute: RecruiterAiRoute,
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterApplicantsRoute: RecruiterApplicantsRoute,
  RecruiterInterviewsRoute: RecruiterInterviewsRoute,
  RecruiterOnboardingRoute: RecruiterOnboardingRoute,
  RecruiterPipelineRoute: RecruiterPipelineRoute,
  RecruiterSettingsRoute: RecruiterSettingsRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
  CandidateJobsJobIdRoute: CandidateJobsJobIdRoute,
  RecruiterCandidatesCandidateIdRoute: RecruiterCandidatesCandidateIdRoute,
  RecruiterJobsJobIdRoute: RecruiterJobsJobIdRoute,
  RecruiterJobsNewRoute: RecruiterJobsNewRoute,
  CandidateJobsIndexRoute: CandidateJobsIndexRoute,
  RecruiterJobsIndexRoute: RecruiterJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
